# defines
SERVER_HTTP_PORT = 80
SERVER_LISTEN_BACKLOG = 10
SERVER_STATIC_HTML="StaticHtmlpage1.html"
SERVER_UP_ONE_DIR_ANCHOR="<A href=\"up\">Up one dir</a>"

#Error Codes
SERVER_ERR_NONE=0
SERVER_ERR_SERV_SOCK_INVALID= -1
SERVER_ERR_REMOTE_SOCK_INVALID=-2 
